[phases.setup]
nixPkgs = ['jdk17']

[phases.build]
cmds = [
    'cd backend',
    'chmod +x gradlew',
    './gradlew clean build -x test'
]

[start]
cmd = 'cd backend && java -jar build/libs/miplan-backend.jar'
